#!/bin/bash
# v12 suite: fine-grain the megakernel KERNEL-CONFIG axis at v10/v11 champion sizing
# (NUM_LAYERS=8, MLP_MULT=2, MATRIX_LR=0.04, MUON_MOMENTUM=0.95, WARMDOWN_ITERS=200).
# int8+zlib val_bpb champion = 1.9039. Sweep warps/stages/block_size/chaos_depth
# with sizing/optimizer pinned.
#
# Config format: "TAG:VORTEX_ENV_OVERRIDES"
# where VORTEX_ENV_OVERRIDES is a space-separated list of KEY=VALUE pairs that
# override the COMMON_ENV defaults (sizing is pinned in COMMON_ENV).

set -u
export DATA_PATH="${DATA_PATH:-/workspace/Fartmagic/data/datasets/fineweb10B_sp8192}"
export TOKENIZER_PATH="${TOKENIZER_PATH:-/workspace/Fartmagic/data/tokenizers/fineweb_8192_bpe.model}"

LOGDIR=/workspace/sota_crawler/logs/v12_suite
mkdir -p "$LOGDIR"
cd /workspace/sota_crawler

# Pinned champion sizing/optimizer. No VORTEX_* kernel vars here — those are
# what each trial sweeps via VORTEX_ENV_OVERRIDES.
COMMON_ENV=(
  VOCAB_SIZE=8192
  ADD_MLP=1
  NUM_HEADS=8
  NUM_KV_HEADS=4
  NUM_LAYERS=8
  MLP_MULT=2
  MATRIX_LR=0.04
  MUON_MOMENTUM=0.95
  WARMDOWN_ITERS=200
  ITERATIONS=300
  VAL_LOSS_EVERY=100
  TRAIN_LOG_EVERY=50
  MAX_WALLCLOCK_SECONDS=3600
  GRAD_CLIP_NORM=0.0
  WARMUP_STEPS=20
)

# Queue: kernel-config sweep around the v10/v11 champion defaults
# (block_size=128, fwd warps=8 stages=3, bwd_chaos warps=8 stages=1,
#  bwd_attn warps=8 stages=3, bwd_attn_dkv warps=8 stages=1, chaos_depth=5).
QUEUE=(
  # BLOCK_SIZE sweep (default 128) — tests tile size
  "blk64:VORTEX_BLOCK_SIZE=64 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "blk256:VORTEX_BLOCK_SIZE=256 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  # FWD stages/warps sweep (default stages=3 warps=8)
  "fwd_st1:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=1 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "fwd_st2:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=2 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "fwd_st4:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=4 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "fwd_w4:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=4 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "fwd_w16:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=16 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  # BWD chaos stages/warps (default stages=1 warps=8)
  "bwd_chaos_st2:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=2 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "bwd_chaos_st3:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=3 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "bwd_chaos_w4:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=4 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  # BWD attn stages (default stages=3)
  "bwd_attn_st1:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=1 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "bwd_attn_st2:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=2 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  "bwd_attn_st4:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=4 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1"
  # BWD attn dkv stages (default stages=1)
  "bwd_dkv_st2:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=2"
  "bwd_dkv_st3:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=3"
  # CHAOS_DEPTH sweep (default 5)
  "chaos_d3:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1 CHAOS_DEPTH=3"
  "chaos_d4:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1 CHAOS_DEPTH=4"
  "chaos_d6:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1 CHAOS_DEPTH=6"
  "chaos_d7:VORTEX_BLOCK_SIZE=128 VORTEX_FWD_NUM_WARPS=8 VORTEX_FWD_NUM_STAGES=3 VORTEX_BWD_CHAOS_NUM_WARPS=8 VORTEX_BWD_CHAOS_NUM_STAGES=1 VORTEX_BWD_ATTN_NUM_WARPS=8 VORTEX_BWD_ATTN_NUM_STAGES=3 VORTEX_BWD_ATTN_DKV_NUM_WARPS=8 VORTEX_BWD_ATTN_DKV_NUM_STAGES=1 CHAOS_DEPTH=7"
)

pids_by_gpu=(0 0 0 0)
tags_by_gpu=("" "" "" "")
QIDX=0
TS() { date -u +%Y-%m-%dT%H:%M:%SZ; }

launch_on() {
  local gpu="$1" cfg="$2"
  IFS=":" read -r tag overrides <<<"$cfg"
  local log="$LOGDIR/v12_${tag}.log"
  local master_port=$((29580 + gpu))
  echo "[v12 $(TS)] GPU$gpu launch tag=$tag ($overrides) -> $log"
  CUDA_VISIBLE_DEVICES="$gpu" env "${COMMON_ENV[@]}" $overrides \
    /venv/main/bin/torchrun --standalone --nproc_per_node=1 \
      --master_port="$master_port" \
      test_vortex_2k.py > "$log" 2>&1 &
  pids_by_gpu[$gpu]=$!
  tags_by_gpu[$gpu]="$tag"
}

gpu_free() {
  local gpu="$1"
  local pid="${pids_by_gpu[$gpu]}"
  if [[ "$pid" -ne 0 ]] && kill -0 "$pid" 2>/dev/null; then
    return 1
  fi
  local mem
  mem=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i "$gpu" 2>/dev/null | tr -d ' ')
  if [[ -z "$mem" ]] || [[ "$mem" -gt 1000 ]]; then
    return 1
  fi
  if [[ "$pid" -ne 0 ]]; then
    echo "[v12 $(TS)] GPU$gpu finished tag=${tags_by_gpu[$gpu]}"
    pids_by_gpu[$gpu]=0
    tags_by_gpu[$gpu]=""
  fi
  return 0
}

echo "[v12 $(TS)] queue=${#QUEUE[@]} trials, dispatching..."

while [[ $QIDX -lt ${#QUEUE[@]} ]]; do
  for gpu in 0 1 2 3; do
    if gpu_free "$gpu"; then
      if [[ $QIDX -lt ${#QUEUE[@]} ]]; then
        launch_on "$gpu" "${QUEUE[$QIDX]}"
        QIDX=$((QIDX + 1))
      fi
    fi
  done
  sleep 10
done

echo "[v12 $(TS)] queue drained, waiting on running trials..."
for gpu in 0 1 2 3; do
  pid="${pids_by_gpu[$gpu]}"
  [[ "$pid" -ne 0 ]] && wait "$pid" || true
done
echo "[v12 $(TS)] all v12 trials finished"
